const express = require('express');
const multer = require('multer');
const {
  processFileUpload,
  generateCaption,
  generateLinkdinPost,
  generateFacebookPost,
  feelingAnalizer,
  generateQuote,
  genrateCustom,
  useTensorFlow,
  generatePrompt,
  generateCode,
} = require('../controllers/fileController.js');
const Type = require('../Type/index.js');
const { GoogleGenerativeAI } = require('@google/generative-ai');
const { GoogleAIFileManager } = require('@google/generative-ai/server');
const fs = require('fs');
const mime = require('mime-types');
const { imageedit } = require('../services/imagegenerationService.js');
const { apikeyController } = require('../controllers/apikeyController.js');
const { checkAndDeductCredit, addCreditInfoToResponse } = require('../middleware/creditMiddleware.js');

// const upload = multer({ dest: 'uploads/' });

const apiKey = process.env.GOOGLE_API_KEY;
const genAI = new GoogleGenerativeAI(apiKey);
const fileManager = new GoogleAIFileManager(apiKey);

const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, 'uploads/');
  },
  filename: function (req, file, cb) {
    cb(
      null,
      file.fieldname +
        '-' +
        Date.now() +
        '.' +
        file.originalname.split('.').pop(),
    );
  },
});

const upload = multer({ storage: storage });

async function uploadToGemini(path, mimeType) {
  const uploadResult = await fileManager.uploadFile(path, {
    mimeType,
    displayName: path,
  });
  const file = uploadResult.file;
  console.log(`Uploaded file ${file.displayName} as: ${file.name}`);
  return file;
}

const model = genAI.getGenerativeModel({
  model: 'gemini-2.5-flash-image',
});

const generationConfig = {
  temperature: 1,
  topP: 0.95,
  topK: 40,
  maxOutputTokens: 8192,
  responseModalities: ['image', 'text'],
  responseMimeType: 'text/plain',
};

const router = express.Router();
router.post('/upload', upload.single('image'), processFileUpload);
router.post('/caption', upload.single('image'), addCreditInfoToResponse, checkAndDeductCredit('captionGeneration'), generateCaption);
router.post('/post', upload.single('image'), addCreditInfoToResponse, checkAndDeductCredit('postGeneration'), generateLinkdinPost);
// router.post('/facebook', upload.single('image'), generateFacebookPost);
router.post('/feeling', upload.single('image'), async (req, res) =>
  feelingAnalizer(req, res, Type.FEELING),
);
router.post('/age', upload.single('image'), async (req, res) =>
  feelingAnalizer(req, res, Type.AGE),
);

router.post('/tree', upload.single('image'), async (req, res) =>
  feelingAnalizer(req, res, Type.TREE),
);
router.post('/animal', upload.single('image'), async (req, res) =>
  feelingAnalizer(req, res, Type.ANIMAL),
);

router.post('/quote', upload.single('image'), async (req, res) =>
  generateQuote(req, res, Type.QUATE),
);

router.post('/custom', async (req, res) =>
  genrateCustom(req, res, Type.CUSTOM),
);
router.post('/story', async (req, res) => genrateCustom(req, res, Type.STORY));

router.post('/mathsolver', upload.single('image'), async (req, res) =>
  generateQuote(req, res, Type.MATHSOLVER),
);

router.post('/report', upload.single('image'), async (req, res) =>
  generateQuote(req, res, Type.MATHSOLVER),
);

router.post('/edit-image', upload.single('image'), addCreditInfoToResponse, checkAndDeductCredit('aiImageEdit'), imageedit);

router.get('/checkPrompt', async (req, res) =>
  generatePrompt(req, res, Type.CheckPrompt),
);

// router.post('/upload', uploadVideo.single('image'), processVideoUpload);

// AI Image Generation endpoint
router.post('/generate-image', addCreditInfoToResponse, checkAndDeductCredit('aiImageGeneration'), async (req, res) => {
  try {
    const { prompt, style } = req.body;

    if (!prompt) {
      return res.status(400).json({
        success: false,
        message: 'Prompt is required for image generation'
      });
    }

    console.log('🎨 Generating image with prompt:', prompt);

    // Generate image using Gemini 2.5 Flash Image model
    const result = await model.generateContent({
      contents: [{
        parts: [
          { text: `Generate an image: ${prompt}${style ? `. Style: ${style}` : ''}` }
        ]
      }],
      generationConfig,
    });

    const response = await result.response;

    // Extract image from response
    const imageParts = response.candidates[0].content.parts.filter(
      part => part.inlineData && part.inlineData.mimeType.startsWith('image/')
    );

    if (imageParts.length === 0) {
      throw new Error('No image was generated by Gemini');
    }

    const imageData = imageParts[0].inlineData.data;
    const imageMimeType = imageParts[0].inlineData.mimeType;
    const imageDataUrl = `data:${imageMimeType};base64,${imageData}`;

    console.log('✅ Image generated successfully with Gemini 2.5 Flash');

    res.json({
      success: true,
      image: imageDataUrl,
      prompt: prompt,
      style: style || 'default',
      message: 'Image generated successfully'
    });

  } catch (error) {
    console.error('❌ Image generation error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to generate image',
      error: error.message
    });
  }
});

router.post('/editImage', upload.single('image'), addCreditInfoToResponse, checkAndDeductCredit('aiImageEdit'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).send('No image file uploaded.');
    }

    const imagePath = req.file.path;
    const mimeType = mime.lookup(imagePath);
    const uploadedFile = await uploadToGemini(imagePath, mimeType);

    const prompt = req.body.prompt;
    if (!prompt) {
      return res.status(400).send('Prompt is required.');
    }

    const parts = [
      {
        inlineData: {
          mimeType: mimeType,
          data: fs.readFileSync(imagePath, 'base64'),
        },
      },
      { text: prompt }, // Corrected prompt format
    ];

    const result = await model.generateContent({
      contents: [{ parts }],
      generationConfig,
    });

    const response = await result.response;

    const textResponse = response.text();
    const imageParts = response.candidates[0].content.parts.filter(
      part => part.inlineData,
    );

    if (imageParts.length > 0) {
      const imageData = imageParts[0].inlineData.data;
      const imageMimeType = imageParts[0].inlineData.mimeType;

      const base64Image = `data:${imageMimeType};base64,${imageData}`;
      res.json({ image: base64Image, text: textResponse });
    } else {
      res.json({ text: textResponse });
    }

    fs.unlinkSync(imagePath);
  } catch (error) {
    console.error('Error processing image:', error);
    res.status(500).send('Error processing image.');
  }
});

// New AI Image Edit endpoint with multi-feature support
router.post('/ai-image-edit', upload.single('image'), addCreditInfoToResponse, checkAndDeductCredit('aiImageEdit'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({
        success: false,
        message: 'No image file uploaded'
      });
    }

    const imagePath = req.file.path;
    const mimeType = mime.lookup(imagePath);

    // Parse edit options from request body
    const {
      textBasedEdit,
      styleTransfer,
      objectManipulation,
      enhancement,
      customPrompt
    } = req.body;

    // Validate that at least one edit type is specified
    if (!textBasedEdit && !styleTransfer && !objectManipulation && !enhancement && !customPrompt) {
      return res.status(400).json({
        success: false,
        message: 'At least one edit option must be specified'
      });
    }

    console.log('🎨 Starting AI image edit with Gemini');
    console.log('Edit options:', { textBasedEdit, styleTransfer, objectManipulation, enhancement });

    // Build comprehensive edit prompt based on selected options
    let editPrompt = 'Edit this image with the following requirements:\n';

    if (textBasedEdit) {
      editPrompt += `Text-based editing: ${textBasedEdit}\n`;
    }

    if (styleTransfer) {
      editPrompt += `Style transfer: Apply ${styleTransfer} style to the image\n`;
    }

    if (objectManipulation) {
      editPrompt += `Object manipulation: ${objectManipulation}\n`;
    }

    if (enhancement) {
      const enhancementOptions = Array.isArray(enhancement) ? enhancement.join(', ') : enhancement;
      editPrompt += `Image enhancement: ${enhancementOptions}\n`;
    }

    if (customPrompt) {
      editPrompt += `Additional instructions: ${customPrompt}\n`;
    }

    editPrompt += '\nReturn the edited image while maintaining the original quality and composition where possible.';

    // Prepare image data for Gemini
    const imageBase64 = fs.readFileSync(imagePath, 'base64');

    const parts = [
      {
        inlineData: {
          mimeType: mimeType,
          data: imageBase64,
        },
      },
      { text: editPrompt }
    ];

    // Call Gemini API
    const result = await model.generateContent({
      contents: [{ parts }],
      generationConfig,
    });

    const response = await result.response;

    // Extract image from response
    const imageParts = response.candidates[0].content.parts.filter(
      part => part.inlineData && part.inlineData.mimeType.startsWith('image/')
    );

    if (imageParts.length === 0) {
      // If no image returned, try to get text response for user feedback
      const textResponse = response.text();
      return res.status(400).json({
        success: false,
        message: 'No edited image was generated. Please try with different edit options.',
        feedback: textResponse
      });
    }

    const editedImageData = imageParts[0].inlineData.data;
    const editedImageMimeType = imageParts[0].inlineData.mimeType;
    const editedImageDataUrl = `data:${editedImageMimeType};base64,${editedImageData}`;

    // Get text response if available
    const textResponse = response.text();

    console.log('✅ Image edited successfully with Gemini');

    // Clean up uploaded file
    fs.unlinkSync(imagePath);

    res.json({
      success: true,
      originalImage: `data:${mimeType};base64,${imageBase64}`,
      editedImage: editedImageDataUrl,
      editOptions: {
        textBasedEdit,
        styleTransfer,
        objectManipulation,
        enhancement,
        customPrompt
      },
      feedback: textResponse,
      message: 'Image edited successfully',
      creditsUsed: 5
    });

  } catch (error) {
    console.error('❌ AI Image Edit error:', error);

    // Clean up uploaded file if it exists
    if (req.file && fs.existsSync(req.file.path)) {
      fs.unlinkSync(req.file.path);
    }

    res.status(500).json({
      success: false,
      message: 'Failed to edit image',
      error: error.message
    });
  }
});

module.exports = router;
