const payuService = require('../services/payuService');
const CreditPackage = require('../../models/CreditPackage');
const PaymentOrder = require('../../models/PaymentOrder');
const Credit = require('../../models/Credit');
const CreditTransaction = require('../../models/CreditTransaction');
const User = require('../../models/User');
const { v4: uuidv4 } = require('uuid');
const validator = require('validator');

class PaymentController {
  /**
   * Get available credit packages
   */
  async getCreditPackages(req, res) {
    try {
      const user = req.user;
      const packages = await CreditPackage.getAvailablePackages(user);

      res.json({
        success: true,
        packages: packages.map(pkg => ({
          id: pkg._id,
          name: pkg.name,
          description: pkg.description,
          credits: pkg.credits,
          bonusCredits: pkg.bonusCredits,
          totalCredits: pkg.totalCredits,
          price: pkg.price,
          currency: pkg.currency,
          originalPrice: pkg.originalPrice,
          pricePerCredit: pkg.pricePerCredit,
          tier: pkg.tier,
          features: pkg.features,
          displaySettings: pkg.displaySettings,
          discountPercentage: pkg.getDiscountPercentage(),
          isAvailable: pkg.isAvailableForUser(user)
        }))
      });
    } catch (error) {
      console.error('Get credit packages error:', error);
      res.status(500).json({
        success: false,
        message: 'Failed to fetch credit packages'
      });
    }
  }

  /**
   * Initiate payment for credit purchase
   */
  async initiatePayment(req, res) {
    try {
      const { packageId, customerDetails } = req.body;
      const userId = req.user._id;

      // Validate request
      if (!packageId) {
        return res.status(400).json({
          success: false,
          message: 'Package ID is required'
        });
      }

      if (!customerDetails || !customerDetails.firstName || !customerDetails.email) {
        return res.status(400).json({
          success: false,
          message: 'Customer details (firstName, email) are required'
        });
      }

      // Validate email
      if (!validator.isEmail(customerDetails.email)) {
        return res.status(400).json({
          success: false,
          message: 'Invalid email address'
        });
      }

      // Check if PayU is configured
      if (!payuService.isConfigured()) {
        return res.status(500).json({
          success: false,
          message: 'Payment service not configured'
        });
      }

      // Get credit package
      const creditPackage = await CreditPackage.findById(packageId);
      if (!creditPackage || !creditPackage.isActive) {
        return res.status(404).json({
          success: false,
          message: 'Credit package not found or inactive'
        });
      }

      // Check if package is available for user
      const user = await User.findById(userId);
      if (!creditPackage.isAvailableForUser(user)) {
        return res.status(403).json({
          success: false,
          message: 'This package is not available for your account'
        });
      }

      // Generate unique transaction ID for PayU
      const txnid = payuService.generateTransactionId();

      // Create PayU payment data
      const payuData = {
        txnid,
        hash: '', // Will be generated by PayU service
        productinfo: `${creditPackage.name} - ${creditPackage.totalCredits} Credits`,
        firstname: customerDetails.firstName,
        email: customerDetails.email,
        phone: customerDetails.phone || '',
        key: payuService.config.merchant.key
      };

      // Create payment order in database
      const paymentOrder = await PaymentOrder.createOrder({
        userId,
        packageId: creditPackage._id,
        amount: creditPackage.price,
        currency: creditPackage.currency,
        creditsToAward: creditPackage.credits,
        bonusCredits: creditPackage.bonusCredits,
        payuData
      });

      // Create PayU payment request
      const paymentRequest = payuService.createPaymentRequest({
        orderId: paymentOrder.orderId,
        amount: creditPackage.price,
        currency: creditPackage.currency,
        customerDetails,
        productInfo: `${creditPackage.name} - ${creditPackage.totalCredits} Credits`,
        udf1: paymentOrder.orderId,
        udf2: 'credit_purchase',
        udf3: userId.toString(),
        udf4: packageId,
        udf5: creditPackage.totalCredits.toString()
      });

      if (!paymentRequest.success) {
        await paymentOrder.updateStatus('failed', {
          failureReason: paymentRequest.error
        });

        return res.status(400).json({
          success: false,
          message: paymentRequest.error
        });
      }

      // Update payment order with PayU data
      await paymentOrder.updateStatus('processing', {
        payuData: {
          ...paymentOrder.payuData,
          hash: paymentRequest.paymentParams.hash
        }
      });

      res.json({
        success: true,
        paymentData: {
          orderId: paymentOrder.orderId,
          txnid: paymentRequest.txnid,
          paymentUrl: paymentRequest.paymentUrl,
          paymentParams: paymentRequest.paymentParams,
          environment: paymentRequest.environment
        },
        packageDetails: {
          name: creditPackage.name,
          credits: creditPackage.credits,
          bonusCredits: creditPackage.bonusCredits,
          totalCredits: creditPackage.totalCredits,
          price: creditPackage.price,
          currency: creditPackage.currency
        }
      });
    } catch (error) {
      console.error('Initiate payment error:', error);
      res.status(500).json({
        success: false,
        message: 'Failed to initiate payment'
      });
    }
  }

  /**
   * Handle PayU payment success callback with enhanced error handling and retry mechanism
   */
  async handlePaymentSuccess(req, res) {
    const requestId = `${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    console.log(`🎉 Processing Payment Success Webhook [${requestId}]:`, {
      txnid: req.body.txnid,
      status: req.body.status,
      amount: req.body.amount
    });

    try {
      const responseData = req.body;

      // Enhanced validation of required fields
      const requiredFields = ['txnid', 'status', 'amount', 'hash'];
      const missingFields = requiredFields.filter(field => !responseData[field]);

      if (missingFields.length > 0) {
        console.error(`❌ Missing required fields [${requestId}]:`, missingFields);
        return res.status(400).json({
          success: false,
          message: `Missing required fields: ${missingFields.join(', ')}`,
          requestId
        });
      }

      // Verify payment response with enhanced security
      const verificationResult = payuService.verifyPaymentResponse(responseData);

      if (!verificationResult.success) {
        console.error(`❌ Payment verification failed [${requestId}]:`, verificationResult.error);

        // Log security issue for monitoring
        if (verificationResult.securityIssue) {
          console.error(`🚨 SECURITY ALERT [${requestId}]: Possible tampering detected`, {
            txnid: responseData.txnid,
            error: verificationResult.error
          });
        }

        return res.status(400).json({
          success: false,
          message: 'Payment verification failed',
          error: verificationResult.error,
          requestId
        });
      }

      const { transactionDetails, isPaymentSuccessful } = verificationResult;

      // Find payment order with enhanced error handling
      const paymentOrder = await PaymentOrder.findByTxnId(transactionDetails.txnid);
      if (!paymentOrder) {
        console.error(`❌ Payment order not found [${requestId}]:`, {
          txnid: transactionDetails.txnid,
          status: transactionDetails.status
        });
        return res.status(404).json({
          success: false,
          message: 'Payment order not found',
          txnid: transactionDetails.txnid,
          requestId
        });
      }

      // Check if webhook already processed to prevent duplicate processing
      if (paymentOrder.webhookProcessed) {
        console.log(`⚠️ Webhook already processed [${requestId}]:`, {
          orderId: paymentOrder.orderId,
          status: paymentOrder.status
        });
        return res.json({
          success: true,
          message: 'Webhook already processed',
          paymentStatus: paymentOrder.status,
          orderId: paymentOrder.orderId,
          creditsAwarded: paymentOrder.creditsAwarded,
          requestId
        });
      }

      // Validate amount consistency
      const expectedAmount = parseFloat(paymentOrder.amount);
      const receivedAmount = parseFloat(transactionDetails.amount);

      if (Math.abs(expectedAmount - receivedAmount) > 0.01) {
        console.error(`❌ Amount mismatch [${requestId}]:`, {
          expected: expectedAmount,
          received: receivedAmount,
          orderId: paymentOrder.orderId
        });
        return res.status(400).json({
          success: false,
          message: 'Amount mismatch detected',
          requestId
        });
      }

      // Update payment order with response data
      await paymentOrder.updateStatus(
        isPaymentSuccessful ? 'success' : 'failed',
        {
          gatewayResponse: responseData,
          webhookRequestId: requestId,
          payuData: {
            ...paymentOrder.payuData,
            mihpayid: transactionDetails.mihpayid,
            mode: transactionDetails.mode,
            status: transactionDetails.status,
            unmappedstatus: transactionDetails.unmappedstatus,
            net_amount_debit: transactionDetails.net_amount_debit,
            discount: transactionDetails.discount,
            addedon: transactionDetails.addedon,
            payment_source: transactionDetails.payment_source,
            bank_ref_num: transactionDetails.bank_ref_num,
            bankcode: transactionDetails.bankcode,
            error: transactionDetails.error,
            error_Message: transactionDetails.error_Message,
            processedAt: new Date()
          }
        }
      );

      // Enhanced credit awarding with rollback capability
      if (isPaymentSuccessful && !paymentOrder.creditsAwarded) {
        try {
          console.log(`💳 Awarding credits [${requestId}]:`, {
            orderId: paymentOrder.orderId,
            userId: paymentOrder.userId,
            creditsToAward: paymentOrder.creditsToAward,
            bonusCredits: paymentOrder.bonusCredits
          });

          // Award credits with atomic transaction
          const creditResult = await this.awardCreditsWithRetry(paymentOrder, requestId);

          if (!creditResult.success) {
            console.error(`❌ Credit awarding failed [${requestId}]:`, creditResult.error);

            // Update order status to indicate credit awarding failed
            await paymentOrder.updateStatus('success', {
              creditAwardingError: creditResult.error,
              creditAwardingAttempts: creditResult.attempts
            });
          } else {
            console.log(`✅ Credits awarded successfully [${requestId}]:`, {
              orderId: paymentOrder.orderId,
              newBalance: creditResult.newBalance,
              transactionId: creditResult.transactionId
            });

            // Update package statistics
            try {
              const creditPackage = await CreditPackage.findById(paymentOrder.packageId);
              if (creditPackage) {
                await creditPackage.recordPurchase(paymentOrder.amount);
                console.log(`📊 Package statistics updated [${requestId}]:`, {
                  packageName: creditPackage.name,
                  totalPurchases: creditPackage.stats.totalPurchases
                });
              }
            } catch (statsError) {
              console.error(`⚠️ Failed to update package statistics [${requestId}]:`, statsError.message);
              // Don't fail the entire process for statistics
            }
          }
        } catch (creditError) {
          console.error(`❌ Critical credit awarding error [${requestId}]:`, creditError);

          // This is a critical error - payment succeeded but credits weren't awarded
          // Log for manual intervention
          console.error(`🚨 MANUAL INTERVENTION REQUIRED [${requestId}]: Payment successful but credit awarding failed`, {
            orderId: paymentOrder.orderId,
            userId: paymentOrder.userId,
            amount: paymentOrder.amount,
            error: creditError.message
          });
        }
      }

      // Mark webhook as processed
      await paymentOrder.markWebhookProcessed();

      const response = {
        success: true,
        paymentStatus: transactionDetails.status,
        orderId: paymentOrder.orderId,
        amount: paymentOrder.amount,
        creditsAwarded: paymentOrder.creditsAwarded,
        transactionId: transactionDetails.txnid,
        mihpayid: transactionDetails.mihpayid,
        requestId,
        processedAt: new Date().toISOString()
      };

      console.log(`✅ Payment success processed [${requestId}]:`, {
        orderId: paymentOrder.orderId,
        status: transactionDetails.status,
        creditsAwarded: paymentOrder.creditsAwarded
      });

      res.json(response);
    } catch (error) {
      console.error(`❌ Payment success handler error [${requestId}]:`, error);
      res.status(500).json({
        success: false,
        message: 'Failed to process payment success',
        error: error.message,
        requestId
      });
    }
  }

  /**
   * Award credits with retry mechanism and atomic transactions
   */
  async awardCreditsWithRetry(paymentOrder, requestId, maxRetries = 3) {
    const userId = paymentOrder.userId;
    const totalCredits = paymentOrder.creditsToAward + paymentOrder.bonusCredits;

    for (let attempt = 1; attempt <= maxRetries; attempt++) {
      try {
        console.log(`🔄 Credit awarding attempt ${attempt}/${maxRetries} [${requestId}]:`, {
          orderId: paymentOrder.orderId,
          userId,
          totalCredits
        });

        // Get user's current credit balance before awarding
        const userCredits = await Credit.findOrCreateForUser(userId);
        const balanceBefore = userCredits.globalCredits.balance;

        // Award credits atomically
        const creditResult = await paymentOrder.awardCredits();

        // Verify credits were actually awarded
        const updatedCredits = await Credit.findOrCreateForUser(userId);
        const balanceAfter = updatedCredits.globalCredits.balance;
        const actualIncrease = balanceAfter - balanceBefore;

        if (actualIncrease !== totalCredits) {
          throw new Error(`Credit awarding mismatch: expected ${totalCredits} but got ${actualIncrease}`);
        }

        // Create detailed transaction record
        const transaction = await CreditTransaction.create({
          userId,
          type: 'purchase',
          paymentOrderId: paymentOrder._id,
          amount: totalCredits,
          balanceBefore,
          balanceAfter,
          description: `Credit purchase - ${paymentOrder.creditsToAward} base + ${paymentOrder.bonusCredits} bonus credits`,
          metadata: {
            packageId: paymentOrder.packageId,
            orderId: paymentOrder.orderId,
            paymentAmount: paymentOrder.amount,
            currency: paymentOrder.currency,
            baseCredits: paymentOrder.creditsToAward,
            bonusCredits: paymentOrder.bonusCredits,
            requestId,
            attempt
          },
          status: 'completed'
        });

        console.log(`✅ Credits awarded successfully on attempt ${attempt} [${requestId}]:`, {
          orderId: paymentOrder.orderId,
          userId,
          balanceBefore,
          balanceAfter,
          actualIncrease,
          transactionId: transaction._id
        });

        return {
          success: true,
          newBalance: balanceAfter,
          transactionId: transaction._id,
          attempts: attempt
        };

      } catch (error) {
        console.error(`❌ Credit awarding attempt ${attempt} failed [${requestId}]:`, error.message);

        if (attempt === maxRetries) {
          // Log final failure for manual intervention
          console.error(`🚨 CREDIT AWARDING FAILED AFTER ${maxRetries} ATTEMPTS [${requestId}]:`, {
            orderId: paymentOrder.orderId,
            userId,
            totalCredits,
            finalError: error.message
          });

          // Create failed transaction record for audit
          try {
            await CreditTransaction.create({
              userId,
              type: 'purchase',
              paymentOrderId: paymentOrder._id,
              amount: totalCredits,
              description: `FAILED: Credit purchase - ${paymentOrder.creditsToAward} base + ${paymentOrder.bonusCredits} bonus credits`,
              metadata: {
                packageId: paymentOrder.packageId,
                orderId: paymentOrder.orderId,
                paymentAmount: paymentOrder.amount,
                currency: paymentOrder.currency,
                baseCredits: paymentOrder.creditsToAward,
                bonusCredits: paymentOrder.bonusCredits,
                requestId,
                attempts: maxRetries,
                finalError: error.message
              },
              status: 'failed'
            });
          } catch (transactionError) {
            console.error(`❌ Failed to create failure transaction record [${requestId}]:`, transactionError.message);
          }

          return {
            success: false,
            error: error.message,
            attempts: maxRetries
          };
        }

        // Wait before retry (exponential backoff)
        const waitTime = Math.pow(2, attempt - 1) * 1000; // 1s, 2s, 4s
        console.log(`⏳ Waiting ${waitTime}ms before retry [${requestId}]`);
        await new Promise(resolve => setTimeout(resolve, waitTime));
      }
    }
  }

  /**
   * Handle PayU payment failure callback with enhanced error handling
   */
  async handlePaymentFailure(req, res) {
    const requestId = `${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    console.log(`❌ Processing Payment Failure Webhook [${requestId}]:`, {
      txnid: req.body.txnid,
      status: req.body.status,
      error: req.body.error_Message || req.body.error
    });

    try {
      const responseData = req.body;

      // Verify payment response (best effort - failures might not have proper hash)
      let verificationResult;
      try {
        verificationResult = payuService.verifyPaymentResponse(responseData);
      } catch (verifyError) {
        console.warn(`⚠️ Payment failure verification skipped [${requestId}]:`, verifyError.message);
        verificationResult = { success: false, transactionDetails: responseData };
      }

      const transactionDetails = verificationResult.transactionDetails || responseData;

      if (!transactionDetails.txnid) {
        console.error(`❌ Missing transaction ID in failure webhook [${requestId}]`);
        return res.status(400).json({
          success: false,
          message: 'Missing transaction ID',
          requestId
        });
      }

      // Find payment order
      const paymentOrder = await PaymentOrder.findByTxnId(transactionDetails.txnid);
      if (!paymentOrder) {
        console.error(`❌ Payment order not found for failure [${requestId}]:`, {
          txnid: transactionDetails.txnid
        });
        return res.status(404).json({
          success: false,
          message: 'Payment order not found',
          txnid: transactionDetails.txnid,
          requestId
        });
      }

      // Check if webhook already processed
      if (paymentOrder.webhookProcessed) {
        console.log(`⚠️ Failure webhook already processed [${requestId}]:`, {
          orderId: paymentOrder.orderId,
          status: paymentOrder.status
        });
        return res.json({
          success: false,
          message: 'Webhook already processed',
          paymentStatus: paymentOrder.status,
          orderId: paymentOrder.orderId,
          requestId
        });
      }

      // Extract failure reason
      const failureReason = transactionDetails.error_Message ||
                           transactionDetails.error ||
                           transactionDetails.unmappedstatus ||
                           'Payment failed';

      // Update payment order status
      await paymentOrder.updateStatus('failed', {
        gatewayResponse: responseData,
        webhookRequestId: requestId,
        failureReason,
        payuData: {
          ...paymentOrder.payuData,
          status: transactionDetails.status,
          error: transactionDetails.error,
          error_Message: transactionDetails.error_Message,
          unmappedstatus: transactionDetails.unmappedstatus,
          processedAt: new Date()
        }
      });

      await paymentOrder.markWebhookProcessed();

      // Log failure for analytics
      console.log(`📊 Payment failure processed [${requestId}]:`, {
        orderId: paymentOrder.orderId,
        userId: paymentOrder.userId,
        amount: paymentOrder.amount,
        failureReason,
        packageId: paymentOrder.packageId
      });

      res.json({
        success: false,
        paymentStatus: 'failed',
        orderId: paymentOrder.orderId,
        transactionId: transactionDetails.txnid,
        error: failureReason,
        requestId,
        processedAt: new Date().toISOString()
      });
    } catch (error) {
      console.error(`❌ Payment failure handler error [${requestId}]:`, error);
      res.status(500).json({
        success: false,
        message: 'Failed to process payment failure',
        error: error.message,
        requestId
      });
    }
  }

  /**
   * Handle PayU payment cancel callback with enhanced error handling
   */
  async handlePaymentCancel(req, res) {
    const requestId = `${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    console.log(`🚫 Processing Payment Cancel Webhook [${requestId}]:`, {
      txnid: req.body.txnid,
      status: req.body.status
    });

    try {
      const responseData = req.body;
      const transactionDetails = responseData;

      if (!transactionDetails.txnid) {
        console.error(`❌ Missing transaction ID in cancel webhook [${requestId}]`);
        return res.status(400).json({
          success: false,
          message: 'Missing transaction ID',
          requestId
        });
      }

      // Find payment order
      const paymentOrder = await PaymentOrder.findByTxnId(transactionDetails.txnid);
      if (!paymentOrder) {
        console.error(`❌ Payment order not found for cancellation [${requestId}]:`, {
          txnid: transactionDetails.txnid
        });
        return res.status(404).json({
          success: false,
          message: 'Payment order not found',
          txnid: transactionDetails.txnid,
          requestId
        });
      }

      // Check if webhook already processed
      if (paymentOrder.webhookProcessed) {
        console.log(`⚠️ Cancel webhook already processed [${requestId}]:`, {
          orderId: paymentOrder.orderId,
          status: paymentOrder.status
        });
        return res.json({
          success: false,
          message: 'Webhook already processed',
          paymentStatus: paymentOrder.status,
          orderId: paymentOrder.orderId,
          requestId
        });
      }

      // Update payment order status
      await paymentOrder.updateStatus('cancelled', {
        gatewayResponse: responseData,
        webhookRequestId: requestId,
        failureReason: 'Payment cancelled by user',
        payuData: {
          ...paymentOrder.payuData,
          status: transactionDetails.status || 'cancelled',
          processedAt: new Date()
        }
      });

      await paymentOrder.markWebhookProcessed();

      // Log cancellation for analytics
      console.log(`📊 Payment cancellation processed [${requestId}]:`, {
        orderId: paymentOrder.orderId,
        userId: paymentOrder.userId,
        amount: paymentOrder.amount,
        packageId: paymentOrder.packageId
      });

      res.json({
        success: false,
        paymentStatus: 'cancelled',
        orderId: paymentOrder.orderId,
        transactionId: transactionDetails.txnid,
        message: 'Payment cancelled by user',
        requestId,
        processedAt: new Date().toISOString()
      });
    } catch (error) {
      console.error(`❌ Payment cancel handler error [${requestId}]:`, error);
      res.status(500).json({
        success: false,
        message: 'Failed to process payment cancellation',
        error: error.message,
        requestId
      });
    }
  }

  /**
   * Get payment analytics and monitoring data
   */
  async getPaymentAnalytics(req, res) {
    try {
      const { timeframe = '7d' } = req.query;

      // Calculate date range
      const endDate = new Date();
      const startDate = new Date();

      switch (timeframe) {
        case '24h':
          startDate.setHours(startDate.getHours() - 24);
          break;
        case '7d':
          startDate.setDate(startDate.getDate() - 7);
          break;
        case '30d':
          startDate.setDate(startDate.getDate() - 30);
          break;
        case '90d':
          startDate.setDate(startDate.getDate() - 90);
          break;
        default:
          startDate.setDate(startDate.getDate() - 7);
      }

      // Aggregate payment data
      const [totalStats, statusBreakdown, packageStats, dailyTrends] = await Promise.all([
        // Total statistics
        PaymentOrder.aggregate([
          {
            $match: {
              createdAt: { $gte: startDate, $lte: endDate }
            }
          },
          {
            $group: {
              _id: null,
              totalOrders: { $sum: 1 },
              totalRevenue: { $sum: { $cond: [{ $eq: ['$status', 'success'] }, '$amount', 0] } },
              totalCreditsAwarded: { $sum: { $cond: [{ $eq: ['$creditsAwarded', true] }, { $add: ['$creditsToAward', '$bonusCredits'] }, 0] } },
              averageOrderValue: { $avg: { $cond: [{ $eq: ['$status', 'success'] }, '$amount', null] } }
            }
          }
        ]),

        // Status breakdown
        PaymentOrder.aggregate([
          {
            $match: {
              createdAt: { $gte: startDate, $lte: endDate }
            }
          },
          {
            $group: {
              _id: '$status',
              count: { $sum: 1 },
              revenue: { $sum: { $cond: [{ $eq: ['$status', 'success'] }, '$amount', 0] } }
            }
          }
        ]),

        // Package performance
        PaymentOrder.aggregate([
          {
            $match: {
              createdAt: { $gte: startDate, $lte: endDate }
            }
          },
          {
            $lookup: {
              from: 'creditpackages',
              localField: 'packageId',
              foreignField: '_id',
              as: 'package'
            }
          },
          {
            $unwind: '$package'
          },
          {
            $group: {
              _id: '$packageId',
              packageName: { $first: '$package.name' },
              totalOrders: { $sum: 1 },
              successfulOrders: { $sum: { $cond: [{ $eq: ['$status', 'success'] }, 1, 0] } },
              totalRevenue: { $sum: { $cond: [{ $eq: ['$status', 'success'] }, '$amount', 0] } },
              creditsAwarded: { $sum: { $cond: [{ $eq: ['$creditsAwarded', true] }, { $add: ['$creditsToAward', '$bonusCredits'] }, 0] } }
            }
          },
          {
            $sort: { totalRevenue: -1 }
          }
        ]),

        // Daily trends
        PaymentOrder.aggregate([
          {
            $match: {
              createdAt: { $gte: startDate, $lte: endDate }
            }
          },
          {
            $group: {
              _id: {
                year: { $year: '$createdAt' },
                month: { $month: '$createdAt' },
                day: { $dayOfMonth: '$createdAt' }
              },
              date: {
                $first: {
                  $dateToString: {
                    format: '%Y-%m-%d',
                    date: '$createdAt'
                  }
                }
              },
              totalOrders: { $sum: 1 },
              successfulOrders: { $sum: { $cond: [{ $eq: ['$status', 'success'] }, 1, 0] } },
              failedOrders: { $sum: { $cond: [{ $eq: ['$status', 'failed'] }, 1, 0] } },
              cancelledOrders: { $sum: { $cond: [{ $eq: ['$status', 'cancelled'] }, 1, 0] } },
              revenue: { $sum: { $cond: [{ $eq: ['$status', 'success'] }, '$amount', 0] } }
            }
          },
          {
            $sort: { '_id.year': 1, '_id.month': 1, '_id.day': 1 }
          }
        ])
      ]);

      // Calculate success rate
      const statusMap = {};
      statusBreakdown.forEach(item => {
        statusMap[item._id] = item.count;
      });

      const totalOrders = Object.values(statusMap).reduce((sum, count) => sum + count, 0);
      const successRate = totalOrders > 0 ? ((statusMap.success || 0) / totalOrders * 100).toFixed(2) : 0;

      // Format response
      const analytics = {
        timeframe,
        dateRange: {
          start: startDate.toISOString(),
          end: endDate.toISOString()
        },
        summary: {
          totalOrders: totalStats[0]?.totalOrders || 0,
          totalRevenue: totalStats[0]?.totalRevenue || 0,
          totalCreditsAwarded: totalStats[0]?.totalCreditsAwarded || 0,
          averageOrderValue: Math.round(totalStats[0]?.averageOrderValue || 0),
          successRate: parseFloat(successRate)
        },
        statusBreakdown: statusBreakdown.map(item => ({
          status: item._id,
          count: item.count,
          revenue: item.revenue,
          percentage: totalOrders > 0 ? ((item.count / totalOrders) * 100).toFixed(2) : 0
        })),
        packagePerformance: packageStats.map(item => ({
          packageId: item._id,
          packageName: item.packageName,
          totalOrders: item.totalOrders,
          successfulOrders: item.successfulOrders,
          totalRevenue: item.totalRevenue,
          creditsAwarded: item.creditsAwarded,
          conversionRate: item.totalOrders > 0 ? ((item.successfulOrders / item.totalOrders) * 100).toFixed(2) : 0
        })),
        dailyTrends: dailyTrends.map(item => ({
          date: item.date,
          totalOrders: item.totalOrders,
          successfulOrders: item.successfulOrders,
          failedOrders: item.failedOrders,
          cancelledOrders: item.cancelledOrders,
          revenue: item.revenue,
          successRate: item.totalOrders > 0 ? ((item.successfulOrders / item.totalOrders) * 100).toFixed(2) : 0
        }))
      };

      res.json({
        success: true,
        analytics
      });
    } catch (error) {
      console.error('Payment analytics error:', error);
      res.status(500).json({
        success: false,
        message: 'Failed to fetch payment analytics'
      });
    }
  }

  /**
   * Get payment status
   */
  async getPaymentStatus(req, res) {
    try {
      const { orderId } = req.params;
      const userId = req.user._id;

      const paymentOrder = await PaymentOrder.findOne({ orderId, userId })
        .populate('packageId', 'name credits bonusCredits totalCredits price')
        .populate('creditTransactionId', 'amount createdAt');

      if (!paymentOrder) {
        return res.status(404).json({
          success: false,
          message: 'Payment order not found'
        });
      }

      res.json({
        success: true,
        order: {
          orderId: paymentOrder.orderId,
          status: paymentOrder.status,
          amount: paymentOrder.amount,
          currency: paymentOrder.currency,
          creditsToAward: paymentOrder.creditsToAward,
          bonusCredits: paymentOrder.bonusCredits,
          creditsAwarded: paymentOrder.creditsAwarded,
          creditsAwardedAt: paymentOrder.creditsAwardedAt,
          packageDetails: paymentOrder.packageId,
          transaction: paymentOrder.creditTransactionId,
          createdAt: paymentOrder.createdAt,
          updatedAt: paymentOrder.updatedAt,
          paymentDetails: {
            txnid: paymentOrder.payuData.txnid,
            mihpayid: paymentOrder.payuData.mihpayid,
            mode: paymentOrder.payuData.mode,
            bank_ref_num: paymentOrder.payuData.bank_ref_num
          }
        }
      });
    } catch (error) {
      console.error('Get payment status error:', error);
      res.status(500).json({
        success: false,
        message: 'Failed to fetch payment status'
      });
    }
  }

  /**
   * Get user's payment history
   */
  async getPaymentHistory(req, res) {
    try {
      const userId = req.user._id;
      const { page = 1, limit = 20, status } = req.query;

      const paymentHistory = await PaymentOrder.getUserPaymentHistory(userId, {
        page: parseInt(page),
        limit: parseInt(limit),
        status
      });

      res.json({
        success: true,
        ...paymentHistory
      });
    } catch (error) {
      console.error('Get payment history error:', error);
      res.status(500).json({
        success: false,
        message: 'Failed to fetch payment history'
      });
    }
  }

  /**
   * Get current user's credit balance
   */
  async getCreditBalance(req, res) {
    try {
      const userId = req.user._id;
      const credits = await Credit.findOrCreateForUser(userId);

      const creditInfo = credits.getUnifiedCreditStatus();

      res.json({
        success: true,
        credits: creditInfo
      });
    } catch (error) {
      console.error('Get credit balance error:', error);
      res.status(500).json({
        success: false,
        message: 'Failed to fetch credit balance'
      });
    }
  }

  /**
   * Migrate user to global credit system
   */
  async migrateToGlobalCredits(req, res) {
    try {
      const userId = req.user._id;
      const credits = await Credit.findOrCreateForUser(userId);

      if (credits.isGlobalCreditsEnabled()) {
        return res.json({
          success: true,
          message: 'User already using global credit system',
          credits: credits.getGlobalCreditInfo()
        });
      }

      await credits.migrateToGlobalCredits();

      res.json({
        success: true,
        message: 'Successfully migrated to global credit system',
        credits: credits.getGlobalCreditInfo()
      });
    } catch (error) {
      console.error('Migrate to global credits error:', error);
      res.status(500).json({
        success: false,
        message: 'Failed to migrate to global credit system'
      });
    }
  }

  /**
   * Get PayU configuration status (for debugging)
   */
  async getPayUConfig(req, res) {
    try {
      // Only allow admins to view config
      if (req.user.role !== 'admin' && req.user.subscription?.plan !== 'admin') {
        return res.status(403).json({
          success: false,
          message: 'Admin access required'
        });
      }

      const configStatus = payuService.getConfigStatus();

      res.json({
        success: true,
        config: configStatus
      });
    } catch (error) {
      console.error('Get PayU config error:', error);
      res.status(500).json({
        success: false,
        message: 'Failed to fetch PayU configuration'
      });
    }
  }

  /**
   * Generate payment form (for direct PayU integration)
   */
  async generatePaymentForm(req, res) {
    try {
      const { orderId } = req.params;
      const userId = req.user._id;

      const paymentOrder = await PaymentOrder.findOne({ orderId, userId, status: 'processing' });
      if (!paymentOrder) {
        return res.status(404).json({
          success: false,
          message: 'Payment order not found or not in processing state'
        });
      }

      const paymentParams = {
        key: paymentOrder.payuData.key,
        txnid: paymentOrder.payuData.txnid,
        amount: paymentOrder.amount.toFixed(2),
        productinfo: paymentOrder.payuData.productinfo,
        firstname: paymentOrder.payuData.firstname,
        email: paymentOrder.payuData.email,
        phone: paymentOrder.payuData.phone,
        currency: paymentOrder.currency,
        hash: paymentOrder.payuData.hash,
        surl: payuService.config.successUrl,
        furl: payuService.config.failureUrl,
        curl: payuService.config.cancelUrl,
        service_provider: 'payu_paisa'
      };

      const paymentForm = payuService.generatePaymentForm(paymentParams, true);

      res.setHeader('Content-Type', 'text/html');
      res.send(paymentForm);
    } catch (error) {
      console.error('Generate payment form error:', error);
      res.status(500).json({
        success: false,
        message: 'Failed to generate payment form'
      });
    }
  }
}

module.exports = new PaymentController();