export const SCREEN_NAME = {
  onBoarding: 'onBoarding',
  HomeTab: 'HomeTab',
  BookTab: 'BookTab',
  PdfViewer: 'PdfViewer',
  Introduction: 'introduction',
  UploadPhoto: 'UploadPhoto',
  QuestionAnswerList: 'QuestionAnswerList',
  AdTestScreen: 'AdTestScreen',
  UploadVideo: 'UploadVideo',
  ToolList: 'ToolList',
  CreateCaption: 'CreateCaption',
  CaptionDetailsList: 'CaptionDetailsList',
  PostCreation: 'PostCreation',
  PostDetailsList: 'PostDetailsList',
  AnalyzeUserFeelings: 'AnalyzeUserFeelings',
  AnalyzeUserFeelingsDetailView: 'AnalyzeUserFeelingsDetailView',
  TreeAnalize: 'TreeAnalize',
  AIPhotoEdit: 'AIPhotoEdit',
  TraditionalPhotoEdit: 'TraditionalPhotoEdit',
  AgeAnalizer: 'AgeAnalizer',
  AgeDetailsScreen: 'AgeDetailsScreen',
  TreeDetailsScreen: 'TreeDetailsScreen',
  AnimalAnalizer: 'AnimalAnalizer',
  AnimalDetailsScreen: 'AnimalDetailsScreen',
  AIImageGeneration: 'AIImageGeneration',
  AIMathSolver: 'AIMathSolver',
  AIMathSolverDetails: 'AIMathSolverDetails',
  LoginFB: 'LoginFB',
  SocialAutomate: 'SocialAutomate',
  VirtualClothTest: 'VirtualClothTest',
  ContentBlocker: 'ContentBlocker',
  GuardianScreen: 'GuardianScreen',
  AIImageEdits: 'AIImageEdits',
  UserProfile: 'UserProfile',
  AIImageEditScreen: 'AIImageEditScreen',
  CreditPurchase: 'CreditPurchase',
  VideoGeneration: 'VideoGeneration',
  TemplateSelection: 'TemplateSelection',
  VideoCustomPrompt: 'VideoCustomPrompt',
  MyVideos: 'MyVideos',
  VideoFavorites: 'VideoFavorites',
  AuthScreen: 'AuthScreen'
};

export const appConstant = {
  shared_prev_Key: {
    keyword_filtering_time: 'keyword_filtering_time',
    keyword_filtering_type: 'diffeculity_type',
    client_id: 'client_id',
    blocking_off_sms: {
      key: 'blocking_off_sms',
      on: 'ON',
      off: 'OFF',
    },
    filter_buckup_phone: 'filter_buckup_phone',
  },

  diffeculity: {
    easy: 'EASY',
    mid: 'MID',
    hard: 'HARD',
  },
};